"""Export engine evidence for a portable, credential-free judge experience."""
from hashlib import sha256
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from bailiff.showcase import SCENARIOS, run_batch, run_scenario
from bailiff.provider_proof import load_provider_proofs


def main():
    bundle = load_provider_proofs(ROOT)
    data = {name: json.loads((ROOT / "outputs" / f"{name}.json").read_text(encoding="utf-8"))
            for name in ("manifest", "aggregate", "sensitivity", "real_interpreter_evidence")}
    batch_path = ROOT / "outputs" / "showcase_batch.json"
    batch_path.write_text(json.dumps(run_batch(), sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8", newline="\n")
    data.update(batch=json.loads(batch_path.read_text(encoding="utf-8")), scenarios={name: run_scenario(name) for name in SCENARIOS},
                provider_proofs={"summary": bundle.summary(), "artifacts": dict(bundle.artifacts)})
    raw = json.dumps(data, sort_keys=True, separators=(",", ":")) + "\n"
    (ROOT / "public" / "evidence.json").write_text(raw, encoding="utf-8", newline="\n")
    print(f"Showcase: {len(data['batch']['receipts'])} cases; SHA256 {sha256(raw.encode()).hexdigest()}")
    batch = data["batch"]
    guarded = next(row for row in batch["summaries"] if row["arm"] == "B3")
    manifest = data["manifest"]
    lines = [
        "<!-- BEGIN GENERATED SUBMISSION METRICS -->",
        "<!-- Generated by scripts/build_showcase.py from outputs/showcase_batch.json and outputs/manifest.json. -->",
        f"The interactive example uses **{batch['n']} cases**, seed **{batch['seed']}**, transient regime, guarded B3 workflow.", "",
        "| Measured in the demo batch | Result |", "|---|---:|",
        f"| Simulated recovered INR | {guarded['recovered_inr']:,.0f} |",
        f"| Simulated provider calls | {guarded['provider_calls']} |",
        f"| Cases routed to human review | {guarded['human_reviews']} |",
        f"| Protected value by denial, synthetic INR | {guarded['protected_value_by_denial_inr']:,.0f} |",
        f"| Legitimate recovery forgone, synthetic INR | {guarded['legitimate_recovery_forgone_inr']:,.0f} |",
        f"| Realized harm, synthetic INR | {guarded['realized_harm_inr']:,.0f} |", "",
        f"The final evaluation covers **{len(manifest['seeds']) * len(manifest['regimes']) * manifest['n_per_seed'] * len(manifest['arms']):,} policy decisions** across **{len(manifest['seeds'])} seeds**, **{len(manifest['regimes'])} regimes**, and **{len(manifest['arms'])} policies**.",
        "<!-- END GENERATED SUBMISSION METRICS -->",
    ]
    for name in ("README.md", "SUBMISSION_READINESS.md"):
        document = ROOT / name
        text = document.read_text(encoding="utf-8")
        start = text.index("<!-- BEGIN GENERATED SUBMISSION METRICS -->")
        end = text.index("<!-- END GENERATED SUBMISSION METRICS -->") + len("<!-- END GENERATED SUBMISSION METRICS -->")
        document.write_text(text[:start] + "\n".join(lines) + text[end:], encoding="utf-8", newline="\n")



if __name__ == "__main__":
    main()
